// frontend/src/lib/components/CollapsibleSection.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	let {
		title,
		badge = '',
		description = '',
		open = $bindable(true),
		children,
	}: {
		title: string;
		badge?: string;
		description?: string;
		open?: boolean;
		children: Snippet;
	} = $props();
</script>

<div class="collapsible" class:open>
	<button class="header" onclick={() => (open = !open)}>
		<span class="chevron">{open ? '\u25BC' : '\u25B6'}</span>
		<span class="title">{title}</span>
		{#if badge}
			<span class="badge">{badge}</span>
		{/if}
	</button>
	{#if description && open}
		<p class="description">{description}</p>
	{/if}
	{#if open}
		<div class="content">
			{@render children()}
		</div>
	{/if}
</div>

<style>
	.collapsible {
		display: flex;
		flex-direction: column;
		background: rgba(255, 255, 255, 0.03);
		border: 1px solid rgba(255, 255, 255, 0.06);
		border-radius: 6px;
		overflow: hidden;
	}
	.header {
		display: flex;
		align-items: center;
		gap: 6px;
		padding: 6px 8px;
		background: none;
		border: none;
		cursor: pointer;
		text-align: left;
		font-family: 'SF Mono', 'Cascadia Code', 'Fira Code', Consolas, monospace;
	}
	.header:hover {
		background: rgba(255, 255, 255, 0.04);
	}
	.chevron {
		font-size: 8px;
		color: rgba(255, 255, 255, 0.4);
		width: 10px;
		flex-shrink: 0;
	}
	.title {
		font-size: 11px;
		font-weight: 600;
		color: rgba(255, 255, 255, 0.7);
		text-transform: uppercase;
		letter-spacing: 0.5px;
	}
	.badge {
		margin-left: auto;
		font-size: 9px;
		padding: 1px 5px;
		border-radius: 8px;
		background: rgba(0, 122, 204, 0.2);
		color: rgba(0, 180, 255, 0.8);
		font-weight: 500;
	}
	.description {
		margin: 0;
		padding: 0 8px 4px;
		font-size: 10px;
		font-style: italic;
		color: rgba(255, 255, 255, 0.35);
		line-height: 1.4;
	}
	.content {
		display: flex;
		flex-direction: column;
		gap: 6px;
		padding: 4px 8px 8px;
	}
</style>

// frontend/src/components/layout/CollapsibleSection.tsx
import type { ReactNode } from 'react';

interface CollapsibleSectionProps {
  title: string;
  badge?: string;
  description?: string;
  open: boolean;
  onToggle: () => void;
  children: ReactNode;
}

export default function CollapsibleSection({
  title,
  badge,
  description,
  open,
  onToggle,
  children,
}: CollapsibleSectionProps) {
  return (
    <div className="flex flex-col bg-white/[0.03] border border-white/[0.06] rounded-md overflow-hidden">
      <button
        className="flex items-center gap-1.5 px-2 py-1.5 bg-transparent border-0 cursor-pointer text-left font-mono hover:bg-white/[0.04]"
        onClick={onToggle}
        aria-expanded={open}
      >
        <span className="text-[8px] text-white/40 w-2.5 shrink-0">
          {open ? '\u25BC' : '\u25B6'}
        </span>
        <span className="text-[11px] font-semibold text-white/70 uppercase tracking-wider">
          {title}
        </span>
        {badge && (
          <span className="ml-auto text-[9px] px-1.5 py-px rounded-full bg-[#007acc]/20 text-[#00b4ff]/80 font-medium">
            {badge}
          </span>
        )}
      </button>
      {description && open && (
        <p className="m-0 px-2 pb-1 text-[10px] italic text-white/35 leading-snug">
          {description}
        </p>
      )}
      {open && (
        <div className="flex flex-col gap-1.5 px-2 pt-1 pb-2">
          {children}
        </div>
      )}
    </div>
  );
}
